# Generated by Django 3.1.7 on 2021-04-08 14:18

import course_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to=course_app.models.thumbnail_upload)),
                ('intro_video_embed_tag', models.TextField()),
                ('support_group_link', models.CharField(blank=True, max_length=99999, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('material_files_link', models.CharField(blank=True, max_length=99999, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty_level', models.CharField(choices=[('All Levels', 'All Levels'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='All Levels', max_length=255)),
                ('course_type', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], default='Paid', max_length=255)),
                ('total_course_duration', models.CharField(default='00:00:00', max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('what_will_i_learn', models.TextField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('material_includes', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255)),
                ('video_embed_tag', models.TextField()),
                ('duration', models.CharField(default='00:00:00', max_length=255)),
                ('privacy_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.module')),
            ],
        ),
    ]
