# Generated by Django 3.1.7 on 2021-04-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_question_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
