# Generated by Django 3.1.7 on 2021-04-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('course_app', '0004_auto_20210410_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('enrollment_status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
        ),
    ]
