# Generated by Django 3.1.7 on 2021-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='completed_student_id',
            field=models.JSONField(default={}),
        ),
    ]
